config/routes.rb
SecretSanta::Application.routes.draw do
  devise_for :people, :skip => [:sessions]

  as :person do
    get 'login' => 'devise/sessions#new', :as => :new_person_session
    post 'login' => 'devise/sessions#create', :as => :person_session
    delete 'logout' => 'devise/sessions#destroy', :as => :destroy_person_session
  end

  get 'profile/:id', to: 'people#show'
  resources :people, only: [:show, :assign_partners]
  get 'assign', to: 'people#assign_partners'

  root 'home#index'

end

app/models/person.rb
class Person < ActiveRecord::Base
  devise :database_authenticatable, :registerable, :validatable
  belongs_to :people, class_name: 'Person', foreign_key: :person_id
  has_one :person, class_name: 'Person', foreign_key: :person_id
  validates_uniqueness_of :username
  validates_presence_of :username, :first_name, :last_name

  def self.secret_santa
    while true
      giftee = self.where(:is_selected => false).first(:order => 'RANDOM()')
      return unless giftee
      gifter = self.where(:person_id => nil).where.not(:id => giftee.id).first(:order => 'RANDOM()')
      return unless gifter
      gifter.person_id   = giftee.id
      giftee.is_selected = true
      giftee.save!
      gifter.save!
    end
  end

  def email_required?
    false
  end

  def email_changed?
    false
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :authenticate_person!, unless: :devise_controller?
  before_filter :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:first_name, :last_name, :username, :password)}
  end

  OPEN_PROFILE_TIME = Time.new(2013,12,6,23,0,0,'-06:00').to_i*1000
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    respond_to do |format|
      format.html
      format.js
      format.json {render :json => {:time => OPEN_PROFILE_TIME}}
    end
  end

end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show], except: [:assign_partners]
  before_filter :restrict_profile_access, only: [:show]

  # GET /people/1
  # GET /people/1.json
  def show
    respond_to do |format|
      format.html
      format.js
    end
  end

  def assign_partners
    respond_to do |format|
      format.js {
        if OPEN_PROFILE_TIME <= Time.now().to_i*1000
          Person.secret_santa
          render :xml => Person.all
        else
          flash[:notice] = "Don't be a jerk Dennis. I know it's you..."
          redirect_to :root
        end
      }
      format.html {
        flash[:notice] = "Don't be a jerk Dennis. I know it's you..."
        redirect_to :root
      }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def person_params
      params.require(:person).permit(:first_name, :last_name)
    end

    def restrict_profile_access
      if current_person != @person
        flash[:error] = "I don't think so #{current_person.first_name}. You can't look at someone else's page."
        redirect_to :root
        return
      end
      if OPEN_PROFILE_TIME > Time.now().to_i*1000
        flash[:error] = "It's not time yet #{current_person.first_name}. I worked my butt off. You can wait :D"
        redirect_to :root
        return
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/home/_show_profile.html.erb
<div id="profile_button">
  <%= link_to 'Ho! Ho! Ho!', person_path(current_person), class: 'btn btn-large btn-danger btn-block', remote: true %>
</div>

app/views/home/index.js.erb
var btn = $('<%= j render 'show_profile' %>');
btn.css('display', 'none');
$('#countdown').append(btn);
btn.fadeIn(1500).delay(2000);

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Secret Santa</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application"%>
  <%= csrf_meta_tags %>
</head>
<body>
<div>
  <div class="btn-group">
    <% if current_person %>
        <%= link_to 'Edit Info', edit_person_registration_path, class: 'btn btn-mini btn-success' %>
        <%= link_to 'Logout', destroy_person_session_path, class: 'btn btn-mini btn-danger', method: :delete %>
    <% end %>
  </div>
</div>
<% if flash[:error] || flash[:notice] %>
      <%= bootstrap_flash %>
<% end %>

<%= yield %>

</body>
</html>

app/views/people/show.html.erb
<%-
    gifter = @person.first_name
    giftee = @person.person_id ? @person.person.first_name : nil
%>
<div class="hero-unit">
    <p>
      <%- if giftee %>
          <span><%= "You Are The Secret Santa For #{giftee}." %></span>
          <br/><br/>
          <%= "Happy Holidays #{gifter}." %>
      <%- else %>
          <%=  'Please wait until a random person is assigned to you.' %>
      <%- end %>
    </p>
</div>

app/views/people/show.js.erb
var response = '<%= j render template: 'people/show.html.erb' %>';
response = $($.parseHTML(response))
response.css('display', 'none');
$('#content_area').fadeOut(700, function(){
    $('#content_area').html(response);
    response.fadeIn(700)
    $('#content_area').fadeIn(700)
});